# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Josh London
email: josh@joshualondon.me
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joshualondon.me" # the base hostname & protocol for your site
twitter_username: joshualondon
github_username:  joshualondon


permalink: notebook/:categories/:title

# Build settings
markdown: kramdown


exclude: ['node_modules', 'Gulpfile.js', 'package.json', 'README.md', '*.sublime-*', '.publish', '.git', 'assets/css', 'assets/js']
keep_files: ["_site/assets"]
